const express = require('express')
const router = express.Router()

const get_achievement = require('./controllers/get_achivement')
const create_tournament = require('./controllers/create_tournament')
const update_tournament = require('./controllers/update_tournament')
const reward_to_user = require('./controllers/reward_to_user')
const get_signed_url_reward_picture = require('./controllers/get_signed_url_reward_picture')
const delete_tournament = require('./controllers/delete_tournament')
const sort_user_by_tournament = require('./controllers/sort_user_by_tournament')
const check_market_status = require('./controllers/market_status')
const { export_tournament, export_order_in_tournament, export_user_in_tournament, export_order_by_user,export_history_username,export_list_user } = require('../src/controllers/export')
const get_rank_in_tournament=require("./controllers/get_rank_in_tournament")

router.post('/check_market_status', check_market_status)
router.post('/get_achievement', get_achievement)
router.post('/create_tournament', create_tournament)
router.post('/update_tournament', update_tournament)
router.post('/reward_to_user', reward_to_user)
router.post('/get_signed_url_reward_picture', get_signed_url_reward_picture)
router.post('/delete-tournament', delete_tournament)
router.post('/sort_user_by_tournament', sort_user_by_tournament)
router.post('/export_tournament', export_tournament)
router.post('/export_order_in_tournament', export_order_in_tournament)
router.post('/export_user_in_tournament', export_user_in_tournament)
router.post('/export_order_by_user', export_order_by_user)
router.post('/get_rank_in_tournament', get_rank_in_tournament)
router.post('/export_history_username', export_history_username)
router.post('/export_list_user', export_list_user)

module.exports = { router }