version: "3.2"
services:

  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672", ";", "echo", "rabbitmq start success"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./.rabbit.env
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    networks:
      - network

networks:
  network:
  
volumes:
  rabbit_data: