version: '3'
services:
  # duplicate 8 demo-account-redis
  data-demo-account-redis:
    image: data-demo-account-redis
    container_name: data-demo-account-redis 
    restart: always
    environment:
        - MICROSERVICE_NAME=DATA_DEMO_ACCOUNT_REDIS
        - TIME_TO_CHECKING_TOURNAMENT_EXP=0 0 8 * * *
    env_file:
      - ./.env
    networks:
      - network

  data-demo-account-redis_1:
    image: data-demo-account-redis
    container_name: data-demo-account-redis_1
    restart: always
    environment:
        - MICROSERVICE_NAME=DATA_DEMO_ACCOUNT_REDIS_CHUNK_1
        - TIME_TO_CHECKING_TOURNAMENT_EXP=0 0 10 * * *
    env_file:
      - ./.env
    networks:
      - network


  data-demo-account-redis_2:
    image: data-demo-account-redis
    container_name: data-demo-account-redis_2
    restart: always
    environment:
        - MICROSERVICE_NAME=DATA_DEMO_ACCOUNT_REDIS_CHUNK_2
        - TIME_TO_CHECKING_TOURNAMENT_EXP=0 0 12 * * *
    env_file:
      - ./.env
    networks:
      - network

  data-demo-account-redis_3:
    image: data-demo-account-redis
    container_name: data-demo-account-redis_3
    restart: always
    environment:
        - MICROSERVICE_NAME=DATA_DEMO_ACCOUNT_REDIS_CHUNK_3
        - TIME_TO_CHECKING_TOURNAMENT_EXP=0 0 14 * * *
    env_file:
      - ./.env
    networks:
      - network

  data-demo-account-redis_4:
    image: data-demo-account-redis
    container_name: data-demo-account-redis_4
    restart: always
    environment:
        - MICROSERVICE_NAME=DATA_DEMO_ACCOUNT_REDIS_CHUNK_4
        - TIME_TO_CHECKING_TOURNAMENT_EXP=0 0 16 * * *
    env_file:
      - ./.env
    networks:
      - network

  data-demo-account-redis_5:
    image: data-demo-account-redis
    container_name: data-demo-account-redis_5
    restart: always
    environment:
        - MICROSERVICE_NAME=DATA_DEMO_ACCOUNT_REDIS_CHUNK_5
        - TIME_TO_CHECKING_TOURNAMENT_EXP=0 0 18 * * *
    env_file:
      - ./.env
    networks:
      - network

  data-demo-account-redis_6:
    image: data-demo-account-redis
    container_name: data-demo-account-redis_6
    restart: always
    environment:
        - MICROSERVICE_NAME=DATA_DEMO_ACCOUNT_REDIS_CHUNK_6
        - TIME_TO_CHECKING_TOURNAMENT_EXP=0 0 20 * * *
    env_file:
      - ./.env
    networks:
      - network

  data-demo-account-redis_7:
    image: data-demo-account-redis
    container_name: data-demo-account-redis_7
    restart: always
    environment:
        - MICROSERVICE_NAME=DATA_DEMO_ACCOUNT_REDIS_CHUNK_7
        - TIME_TO_CHECKING_TOURNAMENT_EXP=0 0 22 * * *
    env_file:
      - ./.env
    networks:
      - network


  # duplicate 10 data-forex-binary-pg

  data-forex-binary-pg:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG
    env_file:
      - ./.env
    networks:
      - network

  data-forex-binary-pg_1:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg_1
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG_CHUNK_1
    env_file:
      - ./.env
    networks:
      - network

  data-forex-binary-pg_2:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg_2
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG_CHUNK_2
    env_file:
      - ./.env
    networks:
      - network

  data-forex-binary-pg_3:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg_3
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG_CHUNK_3
    env_file:
      - ./.env
    networks:
      - network

  data-forex-binary-pg_4:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg_4
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG_CHUNK_4
    env_file:
      - ./.env
    networks:
      - network


  data-forex-binary-pg_5:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg_5
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG_CHUNK_5
    env_file:
      - ./.env
    networks:
      - network

  data-forex-binary-pg_6:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg_6
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG_CHUNK_6
    env_file:
      - ./.env
    networks:
      - network

  data-forex-binary-pg_7:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg_7
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG_CHUNK_7
    env_file:
      - ./.env
    networks:
      - network

  data-forex-binary-pg_8:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg_8
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG_CHUNK_8
    env_file:
      - ./.env
    networks:
      - network

  data-forex-binary-pg_9:
    image: data-forex-binary-pg
    container_name: data-forex-binary-pg_9
    restart: always
    environment:
      - MICROSERVICE_NAME=DATA_FOREX_BINARY_PG_CHUNK_9
    env_file:
      - ./.env
    networks:
      - network
    
networks:
  network:
