version: '3'
services:


  # duplicate services logic binary
  logic-binary-forex-1:
    image: logic-binary
    container_name: logic-binary-forex-1
    restart: always
    environment:
      - MICROSERVICE_NAME=LOGIC_BINARY_FOREX_CHUNK_1
      - CHUNK_ORDER_BINARY_LIST=4
      - CHUNK_PICE_ORDER_BINARY=1
      - PRICE_TYPE=forex
    env_file:
      - ./.env
    networks:
      - network

  logic-binary-forex-2:
    image: logic-binary
    container_name: logic-binary-forex-2
    restart: always
    environment:
      - MICROSERVICE_NAME=LOGIC_BINARY_FOREX_CHUNK_2
      - CHUNK_ORDER_BINARY_LIST=4
      - CHUNK_PICE_ORDER_BINARY=2
      - PRICE_TYPE=forex
    env_file:
      - ./.env
    networks:
      - network

  logic-binary_forex-3:
    image: logic-binary
    container_name: logic-binary-forex-3
    restart: always
    environment:
      - MICROSERVICE_NAME=LOGIC_BINARY_FOREX_CHUNK_3
      - CHUNK_ORDER_BINARY_LIST=4
      - CHUNK_PICE_ORDER_BINARY=3
      - PRICE_TYPE=forex
    env_file:
      - ./.env
    networks:
      - network

  logic-binary_forex-4:
    image: logic-binary
    container_name: logic-binary-forex-4
    restart: always
    environment:
      - MICROSERVICE_NAME=LOGIC_BINARY_FOREX_CHUNK_4
      - CHUNK_ORDER_BINARY_LIST=4
      - CHUNK_PICE_ORDER_BINARY=4
      - PRICE_TYPE=forex
    env_file:
      - ./.env
    networks:
      - network

  # binary stock 
  logic-binary-stock-1:
    image: logic-binary
    container_name: logic-binary-stock-1
    restart: always
    environment:
      - MICROSERVICE_NAME=LOGIC_BINARY_STOCK_CHUNK_1
      - CHUNK_ORDER_BINARY_LIST=1
      - CHUNK_PICE_ORDER_BINARY=1
      - PRICE_TYPE=stock
    env_file:
      - ./.env
    networks:
      - network

  # binary crypto
  logic-binary-crypto-1:
    image: logic-binary
    container_name: logic-binary-crypto-1
    restart: always
    environment:
      - MICROSERVICE_NAME=LOGIC_BINARY_CRYPTO_CHUNK_1
      - CHUNK_ORDER_BINARY_LIST=2
      - CHUNK_PICE_ORDER_BINARY=1
      - PRICE_TYPE=crypto
    env_file:
      - ./.env
    networks:
      - network

  logic-binary-crypto-2:
    image: logic-binary
    container_name: logic-binary-crypto-2
    restart: always
    environment:
      - MICROSERVICE_NAME=LOGIC_BINARY_CRYPTO_CHUNK_2
      - CHUNK_ORDER_BINARY_LIST=2
      - CHUNK_PICE_ORDER_BINARY=2
      - PRICE_TYPE=crypto
    env_file:
      - ./.env
    networks:
      - network


  # binary commodity 
  logic-binary-commodity-1:
    image: logic-binary
    container_name: logic-binary-commodity-1
    restart: always
    environment:
      - MICROSERVICE_NAME=LOGIC_BINARY_COMMODITY_CHUNK_1
      - CHUNK_ORDER_BINARY_LIST=1
      - CHUNK_PICE_ORDER_BINARY=1
      - PRICE_TYPE=commodity
    env_file:
      - ./.env
    networks:
      - network

  # duplicate handle active => crypto, stock, commodity
  logic-active-commodity:
    image: logic-active
    container_name: logic-active-commodity
    restart: always
    environment:
      - PRICE_TYPE=commodity
    env_file:
      - ./.env
    networks:
      - network


  logic-active-stock:
    image: logic-active
    container_name: logic-active-stock
    restart: always
    environment:
      - PRICE_TYPE=stock
    env_file:
      - ./.env
    networks:
      - network

  logic-active-crypto:
    image: logic-active
    container_name: logic-active-crypto
    restart: always
    environment:
      - PRICE_TYPE=crypto
    env_file:
      - ./.env
    networks:
      - network


  # duplicate handle margin => crypto, commodity, stock
  logic-margin-commodity:
    image: logic-margin
    container_name: logic-margin-commodity
    restart: always
    environment:
      - PRICE_TYPE=commodity
    env_file:
      - ./.env
    networks:
      - network

  logic-margin-stock:
    image: logic-margin
    container_name: logic-margin-stock
    restart: always
    environment:
      - PRICE_TYPE=stock
    env_file:
      - ./.env
    networks:
      - network

  logic-margin-crypto:
    image: logic-margin
    container_name: logic-margin-crypto
    restart: always
    environment:
      - PRICE_TYPE=crypto
    env_file:
      - ./.env
    networks:
      - network


  # duplicate handle pending => crypto, forex, stock
  logic-pending-commodity:
    image: logic-pending
    container_name: logic-pending-commodity
    restart: always
    environment:
      - PRICE_TYPE=commodity
    env_file:
      - ./.env
    networks:
      - network

  logic-pending-stock:
    image: logic-pending
    container_name: logic-pending-stock
    restart: always
    environment:
      - PRICE_TYPE=stock
    env_file:
      - ./.env
    networks:
      - network

  logic-pending-crypto:
    image: logic-pending
    container_name: logic-pending-crypto
    restart: always
    environment:
      - PRICE_TYPE=crypto
    env_file:
      - ./.env
    networks:
      - network

  data-cron-swap:
    image: data-cron-swap
    container_name: data-cron-swap
    restart: always
    build:
      context: ./microservices/schedule_swap_order
    env_file:
      - ./.env
    networks:
      - network

networks:
  network:
  